version: '3.3'

services:
  user:
    build: ./User
    restart: always
    depends_on:
      - 'user-db'
    ports:
      - 8001:8000
    volumes:
      - "./User:/app"
  user-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "/opt/data/user:/var/lib/mysql"
  restaurant:
    build: ./Restaurant
    restart: always
    depends_on:
      - 'restaurant-db'
    ports:
      - 8002:8000
    volumes:
      - "./Restaurant:/app"
  restaurant-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "/opt/data/restaurant:/var/lib/mysql"
  coupon:
    build: ./Coupon
    restart: always
    depends_on:
      - 'user'
    ports:
      - '8003:3000'
    volumes:
      - './Coupon:/app'
      - /app/node_modules/
  coupon-db:
    image: mongo
    restart: always
    command: mongod --bind_ip 0.0.0.0
    volumes:
      - "/opt/data/coupon:/data/db"
  event-bus:
    image: rabbitmq:alpine
    restart: always