apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-db-depl
  labels:
    app: restaurant-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-db
  template:
    metadata:
      labels:
        app: restaurant-db
    spec:
      containers:
        - name: restaurant-db
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-db-srv
spec:
  selector:
    name: restaurant-db
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306